{
  "mode": "public",
  "changeLang": "en",
  "antiCall": "group",
  "ownerNumber": "+254105012274",
  "ownerName": "Navine",
  "ownerFrom": "Kenya",
  "ownerAge": "2",
  "menuLogo": null,
  "aliveLogo": null,
  "ownerLogo": null,
  "autoTyping": true,
  "autoRecording": false,
  "antiDelete": true,
  "statusRead": false,
  "statusReact": false,
  "autoRead": false,
  "cmdRead": false,
  "autoBlock": false,
  "autoVoice": false,
  "autoContact": true,
  "alwaysOnline": false
}