{
  "mode": "public",
  "changeLang": "en",
  "antiCall": "off",
  "ownerNumber": "+263780028799",
  "ownerName": "Skelter25",
  "ownerFrom": "JAPAN",
  "ownerAge": "21",
  "menuLogo": null,
  "aliveLogo": null,
  "ownerLogo": null,
  "autoTyping": false,
  "autoRecording": true,
  "antiDelete": true,
  "statusRead": true,
  "statusReact": true,
  "autoRead": true,
  "cmdRead": true,
  "autoBlock": true,
  "autoVoice": true,
  "autoContact": true,
  "alwaysOnline": true
}