{
  "mode": "public",
  "changeLang": "en",
  "antiCall": "off",
  "ownerNumber": "+263780028799",
  "ownerName": "Skelter25",
  "ownerFrom": "Zimbabwe",
  "ownerAge": "21",
  "menuLogo": "https://i.ibb.co/PGDctjps/1758782332387.jpg",
  "aliveLogo": "https://i.ibb.co/d0r8bbdF/bot-image.jpg",
  "ownerLogo": "https://i.ibb.co/F43RgCR5/1758782287435.jpg",
  "autoTyping": true,
  "autoRecording": false,
  "antiDelete": true,
  "statusRead": true,
  "statusReact": true,
  "autoRead": true,
  "cmdRead": true,
  "autoBlock": true,
  "autoVoice": true,
  "autoContact": true,
  "alwaysOnline": true
}