{
  "mode": "public",
  "changeLang": "en",
  "antiCall": "all",
  "ownerNumber": "+918209397203",
  "ownerName": "Ravan",
  "ownerFrom": "India",
  "ownerAge": "23",
  "menuLogo": null,
  "aliveLogo": null,
  "ownerLogo": null,
  "autoTyping": false,
  "autoRecording": true,
  "antiDelete": true,
  "statusRead": true,
  "statusReact": true,
  "autoRead": true,
  "cmdRead": true,
  "autoBlock": true,
  "autoVoice": true,
  "autoContact": true,
  "alwaysOnline": true
}