{
  "mode": "public",
  "changeLang": "en",
  "antiCall": "off",
  "ownerNumber": "+923240219215",
  "ownerName": "Mr Zain",
  "ownerFrom": "Pakistan",
  "ownerAge": "+9999",
  "menuLogo": "https://i.ibb.co/hxHcCQQS/IMG-20250807-125918-445.jpg",
  "aliveLogo": "https://i.ibb.co/hxHcCQQS/IMG-20250807-125918-445.jpg",
  "ownerLogo": null,
  "autoTyping": false,
  "autoRecording": false,
  "antiDelete": false,
  "statusRead": true,
  "statusReact": true,
  "autoRead": false,
  "cmdRead": false,
  "autoBlock": false,
  "autoVoice": false,
  "autoContact": false,
  "alwaysOnline": false
}