{
  "mode": "private",
  "changeLang": "en",
  "antiCall": "off",
  "ownerNumber": "+94769186177",
  "ownerName": "PATHUM",
  "ownerFrom": "Weligalla",
  "ownerAge": "+18",
  "menuLogo": "https://i.ibb.co/KpmR4fLD/1000045353.jpg",
  "aliveLogo": "https://i.ibb.co/8LDvCLk0/1000045354.jpg",
  "ownerLogo": "https://i.ibb.co/8LDvCLk0/1000045354.jpg",
  "autoTyping": false,
  "autoRecording": false,
  "antiDelete": true,
  "statusRead": true,
  "statusReact": true,
  "autoRead": false,
  "cmdRead": false,
  "autoBlock": false,
  "autoVoice": false,
  "autoContact": false,
  "alwaysOnline": false
}