{
  "mode": "public",
  "changeLang": "en",
  "antiCall": "off",
  "ownerNumber": "+94760490500",
  "ownerName": "Kasun",
  "ownerFrom": "Sri lanka",
  "ownerAge": "19",
  "menuLogo": null,
  "aliveLogo": null,
  "ownerLogo": null,
  "autoTyping": true,
  "autoRecording": false,
  "antiDelete": true,
  "statusRead": true,
  "statusReact": true,
  "autoRead": true,
  "cmdRead": true,
  "autoBlock": false,
  "autoVoice": false,
  "autoContact": true,
  "alwaysOnline": false
}